.\"Created with GNOME Manpages Editor Wizard
.\"http://gmanedit.sourceforge.net
.\"Sergio Rua <srua@gpul.org>
.\"
.TH update-dccmaps 8 "November 20th, 2004"

.SH NAME
update-dccmaps \- regenerate DCC map-file

.SH SYNOPSIS
.B update-dccmaps
.RI [\ no\ parameters\ ]
.br

.SH DESCRIPTION
.B update-dccmaps
regenerates /var/lib/dcc/map file from /etc/dcc/map.txt

.SH BUGS
None known. If you find some, please report to Martin Zobel-Helas <mhelas@helas.net>.

.SH SEE ALSO
dccd(8)

.SH AUTHOR
Martin Zobel-Helas <mhelas@helas.net>
